# permissions for end users to edit mypythons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mypython-editor-role
rules:
- apiGroups:
  - example.com
  resources:
  - mypythons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com
  resources:
  - mypythons/status
  verbs:
  - get
