# permissions for end users to view mypythons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mypython-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - mypythons
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - mypythons/status
  verbs:
  - get
